import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';

import { cn } from '@/lib/utils';
import { ConvexWithClerkClientProvider } from '@/providers/convex-client-provider';

import { Toaster } from '@/components/ui/sonner';
import { ModalProvider } from '@/providers/modal-provider';
import { Suspense } from 'react';
import Loading from '@/components/Loading';
import HomeNavbar from '@/components/Navbar/HomeNavbar';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Board',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='icon'
          href='/logo.svg'
          sizes='any'
        />
      </head>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased grainy',
          fontSans.variable
        )}
      >
        <Suspense fallback={<Loading />}>
          <ConvexWithClerkClientProvider>
            <Toaster />
            <ModalProvider />
            <HomeNavbar />
            {children}
          </ConvexWithClerkClientProvider>
        </Suspense>
      </body>
    </html>
  );
}
